from PyQt5 import QtCore, QtGui, QtWidgets
import configparser


class WelcomeView(object):

    def __init__(self, MainWindow):
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralWidget)
        self.widget_2 = QtWidgets.QWidget(self.centralWidget)
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget_2)
        self.projectOptionButton = QtWidgets.QPushButton(self.widget_2)
        self.customiseOptionButton = QtWidgets.QPushButton(self.widget_2)
        self.licenseOptionButton = QtWidgets.QPushButton(self.widget_2)
        self.mainWidget = QtWidgets.QGridLayout()
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_5 = QtWidgets.QLabel(self.centralWidget)
        self.widget = QtWidgets.QWidget(self.centralWidget)
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.openButton = QtWidgets.QPushButton(self.widget)
        self.newProjectLabel = QtWidgets.QLabel(self.widget)
        self.openLabel = QtWidgets.QLabel(self.widget)
        self.tableWidget = QtWidgets.QTableWidget(self.centralWidget)
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.newProjectButton = QtWidgets.QPushButton(self.widget)

        self.configGeneral = configparser.RawConfigParser()
        self.configGeneral.read('./Languages/AppConfigGeneral.cfg')
        self.config = configparser.RawConfigParser()
        self.config.read('./Languages/AppConfig' + self.configGeneral.get('LANGUAGE', 'code') + '.cfg')

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1216, 889)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralWidget.setObjectName("centralwidget")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(200, 600))
        self.widget_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.widget_2.setStyleSheet("background-color: rgb(59, 91, 134);border: none;")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_4.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.pushButton_4.setStyleSheet("border: none;\n"
                                        "font: 75 8pt \"MS Shell Dlg 2\";\n"
                                        "    color: palette(window-text);\n"
                                        "    background: transparent;\n"
                                        "font: 8pt \"Cascadia Mono\";")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon)
        self.pushButton_4.setIconSize(QtCore.QSize(50, 80))
        self.pushButton_4.setDefault(False)
        self.pushButton_4.setFlat(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)
        spacerItem = QtWidgets.QSpacerItem(20, 25, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem)
        self.projectOptionButton.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono")
        font.setPointSize(9)
        self.projectOptionButton.setFont(font)
        self.projectOptionButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.projectOptionButton.setStyleSheet("background-color: rgb(32, 111, 209);\n"
                                               "border: none;")
        self.projectOptionButton.setIconSize(QtCore.QSize(0, 0))
        self.projectOptionButton.setAutoDefault(False)
        self.projectOptionButton.setDefault(True)
        self.projectOptionButton.setFlat(False)
        self.projectOptionButton.setObjectName("pushButton_5")
        self.verticalLayout.addWidget(self.projectOptionButton)
        self.customiseOptionButton.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono")
        font.setPointSize(9)
        self.customiseOptionButton.setFont(font)
        self.customiseOptionButton.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.customiseOptionButton)
        self.licenseOptionButton.setMinimumSize(QtCore.QSize(0, 25))
        self.licenseOptionButton.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono")
        font.setPointSize(9)
        self.licenseOptionButton.setFont(font)
        self.licenseOptionButton.setObjectName("pushButton_6")
        self.verticalLayout.addWidget(self.licenseOptionButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout.addWidget(self.widget_2)
        self.mainWidget.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.mainWidget.setObjectName("mainWidget")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.mainWidget.addItem(spacerItem2, 6, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.mainWidget.addItem(spacerItem3, 10, 1, 1, 1)
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono")
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.mainWidget.addWidget(self.label, 4, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.mainWidget.addItem(spacerItem4, 5, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.mainWidget.addItem(spacerItem5, 2, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 200, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.mainWidget.addItem(spacerItem6, 0, 1, 1, 1)
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono")
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.mainWidget.addWidget(self.label_4, 3, 1, 1, 1)
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.mainWidget.addWidget(self.label_5, 1, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.mainWidget.addItem(spacerItem7, 6, 2, 1, 1)
        self.widget.setMinimumSize(QtCore.QSize(0, 100))
        self.widget.setObjectName("widget")
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem8, 0, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem9, 0, 4, 1, 1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openButton.sizePolicy().hasHeightForWidth())
        self.openButton.setSizePolicy(sizePolicy)
        self.openButton.setMinimumSize(QtCore.QSize(80, 80))
        self.openButton.setMaximumSize(QtCore.QSize(100, 100))
        self.openButton.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.openButton.setStyleSheet("QPushButton {\n"
                                      "    border: 0px solid;\n"
                                      "    border-radius: 10px;\n"
                                      "    background-color: rgb(59, 91, 134);\n"
                                      "    padding-right:0px;\n"
                                      "    padding-left: 0px;\n"
                                      "}")
        self.openButton.setInputMethodHints(QtCore.Qt.ImhNone)
        self.openButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("descarga.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openButton.setIcon(icon1)
        self.openButton.setIconSize(QtCore.QSize(80, 80))
        self.openButton.setObjectName("openButton")
        self.gridLayout_3.addWidget(self.openButton, 0, 3, 1, 1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newProjectButton.sizePolicy().hasHeightForWidth())
        self.newProjectButton.setSizePolicy(sizePolicy)
        self.newProjectButton.setMinimumSize(QtCore.QSize(80, 80))
        self.newProjectButton.setMaximumSize(QtCore.QSize(100, 100))
        self.newProjectButton.setSizeIncrement(QtCore.QSize(80, 100))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.newProjectButton.setFont(font)
        self.newProjectButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.newProjectButton.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.newProjectButton.setAcceptDrops(False)
        self.newProjectButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.newProjectButton.setStyleSheet("QPushButton {\n"
                                            "    border: 0px solid;\n"
                                            "    border-radius: 10px;\n"
                                            "    background-color: rgb(32, 111, 209);\n"
                                            "    padding-right:0px;\n"
                                            "    padding-left: 0px;"
                                            "}")
        self.newProjectButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("newProject.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.newProjectButton.setIcon(icon2)
        self.newProjectButton.setIconSize(QtCore.QSize(50, 50))
        self.newProjectButton.setFlat(False)
        self.newProjectButton.setObjectName("newProjectButton")
        self.gridLayout_3.addWidget(self.newProjectButton, 0, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem10, 0, 2, 1, 1)
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono")
        self.newProjectLabel.setFont(font)
        self.newProjectLabel.setObjectName("newProjectLabel")
        self.gridLayout_3.addWidget(self.newProjectLabel, 1, 1, 1, 1)
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono")
        font.setPointSize(8)
        self.openLabel.setFont(font)
        self.openLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.openLabel.setObjectName("opnLabel")
        self.gridLayout_3.addWidget(self.openLabel, 1, 3, 1, 1)
        self.mainWidget.addWidget(self.widget, 6, 1, 1, 1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tableWidget.setLineWidth(0)
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget.setAutoScroll(False)
        self.tableWidget.setAutoScrollMargin(17)
        self.tableWidget.setTabKeyNavigation(False)
        self.tableWidget.setDragDropOverwriteMode(False)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setGridStyle(QtCore.Qt.DotLine)
        self.tableWidget.setWordWrap(False)
        self.tableWidget.setCornerButtonEnabled(False)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono")
        item.setFont(font)
        item.setBackground(QtGui.QColor(60, 92, 134))
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono")
        item.setFont(font)
        item.setBackground(QtGui.QColor(60, 92, 134))
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono")
        item.setFont(font)
        item.setBackground(QtGui.QColor(60, 92, 134))
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(125)
        self.tableWidget.horizontalHeader().setHighlightSections(False)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(60)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(50)
        self.tableWidget.verticalHeader().setMinimumSectionSize(30)
        self.mainWidget.addWidget(self.tableWidget, 9, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.mainWidget.addItem(spacerItem11, 7, 1, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.mainWidget.addItem(spacerItem12, 9, 2, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.mainWidget.addItem(spacerItem13, 9, 0, 1, 1)
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono")
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.mainWidget.addWidget(self.label_2, 8, 1, 1, 1)
        self.horizontalLayout.addLayout(self.mainWidget)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1216, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.projectOptionButton.clicked.connect(lambda: self.moveToWelcomeViewOptions(1))
        self.customiseOptionButton.clicked.connect(lambda: self.moveToWelcomeViewOptions(2))
        self.licenseOptionButton.clicked.connect(lambda: self.moveToWelcomeViewOptions(3))

    def moveToWelcomeViewOptions(self, chooseButtonIdentifier):
        self.projectOptionButton.setStyleSheet("border: none;")
        self.customiseOptionButton.setStyleSheet("border: none;")
        self.licenseOptionButton.setStyleSheet("border: none;")

        if chooseButtonIdentifier == 1:
            self.projectOptionButton.setStyleSheet("background-color: rgb(32, 111, 209); border: none;")
        elif chooseButtonIdentifier == 2:
            self.customiseOptionButton.setStyleSheet("background-color: rgb(32, 111, 209); border: none;")
        elif chooseButtonIdentifier == 3:
            self.licenseOptionButton.setStyleSheet("background-color: rgb(32, 111, 209); border: none;")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_4.setText(_translate("MainWindow", "  SpyDocument\n"
                                                           "  v2022.1"))
        self.projectOptionButton.setText(_translate("MainWindow", str(self.config.get('WelcomeViewSection',
                                                                                      'projectOptionButton_text'))
                                         .encode('ansi')))
        self.customiseOptionButton.setText(_translate("MainWindow", str(self.config.get('WelcomeViewSection',
                                                                                        'customiseOptionButton_text'))
                                                      .encode('ansi')))
        self.licenseOptionButton.setText(_translate("MainWindow", "License"))
        self.label.setText(_translate("MainWindow", "Open existing project from the disk to continue developing it."))
        self.label_4.setText(_translate("MainWindow", "Create new project to start to research and explore."))
        self.label_5.setText(_translate("MainWindow", "Welcome to SpyDocument"))
        self.newProjectLabel.setText(_translate("MainWindow", "New Project"))
        self.openLabel.setText(_translate("MainWindow", str(self.config.get('WelcomeViewSection', 'openButton_text'))
                                          .encode('ansi')))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Project Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Access"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Location"))
        self.label_2.setText(_translate("MainWindow", "Recent Activity"))
